In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3])
print(a)
print(a.shape)
b= np.array([
    [1,2,3],
    [4,5,6]
])
print(b)
print(b.shape)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
c = np.arange(1,10, .2)
print(c)
print(c.shape)
d = np.linspace(1,10,10)
print(d)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [9]:
print(c.reshape(3,3,5))

[[[1.  1.2 1.4 1.6 1.8]
  [2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]
  [6.  6.2 6.4 6.6 6.8]]

 [[7.  7.2 7.4 7.6 7.8]
  [8.  8.2 8.4 8.6 8.8]
  [9.  9.2 9.4 9.6 9.8]]]


In [10]:
np.random.randint(1,1000,(3,3))

array([[ 91, 655, 322],
       [430, 818, 563],
       [724, 860, 404]])

In [11]:
#maths in numpy

x = np.array([
    [2,3,4],
    [5,6,7]
])

y = np.array([
    [1,3,5],
    [8,6,4]
])

In [12]:
print(x + y) # element wise addition
print(x - y) # element wise addition
print(x / y) # element wise addition
print(x * y) # element wise addition
print(x ** y) # element wise addition
print(x % y) # element wise addition

[[ 3  6  9]
 [13 12 11]]
[[ 1  0 -1]
 [-3  0  3]]
[[2.    1.    0.8  ]
 [0.625 1.    1.75 ]]
[[ 2  9 20]
 [40 36 28]]
[[     2     27   1024]
 [390625  46656   2401]]
[[0 0 4]
 [5 0 3]]


In [13]:
#matrix multiplication
print(x.dot(y.T))
print(np.matmul(x,y.T))
print(x @ y.T)

[[ 31  50]
 [ 58 104]]
[[ 31  50]
 [ 58 104]]
[[ 31  50]
 [ 58 104]]


In [14]:
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.argmax ())
print(x.argmin())

27
[ 7  9 11]
[ 9 18]
4.5
1.707825127659933
2
7
5
0


In [15]:
# trigonometric
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))


[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866 ]]
[[-0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225]]
[[-2.18503986 -0.14254654  1.15782128]
 [-3.38051501 -0.29100619  0.87144798]]
[[nan nan nan]
 [nan nan nan]]


C:\Users\SHRADDHA SINGH\AppData\Local\Temp\ipykernel_13080\252134562.py:5: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))


In [16]:
#indexing
print(x[0,0])
print(x[0,:])
print(x[:,0])
print(x[:2,:2])
print(x[:2])

2
[2 3 4]
[2 5]
[[2 3]
 [5 6]]
[[2 3 4]
 [5 6 7]]
